# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aixgate < Formula
  desc "A deny-by-default sandbox for AI coding agents (Claude Code, Cursor, Aider, Codex)."
  homepage "https://github.com/aixgo-dev/aixgate"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "326c7efb983fb139d7954af87ff9a6b99ebb0af05d85749924a5c7158440f3c5"

      define_method(:install) do
        bin.install "aixgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Darwin_arm64.tar.gz"
      sha256 "e75adf50af7e4b37e2249cad5583399dad4beb0569d347aacf137decb3b9cd5e"

      define_method(:install) do
        bin.install "aixgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Linux_x86_64.tar.gz"
      sha256 "ea2a63e76fd1bebd5ee64f40b5b13bba28330fb21a5f7a50b6ae90a9d86dcbd7"
      define_method(:install) do
        bin.install "aixgate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Linux_arm64.tar.gz"
      sha256 "7ec5a5dc3bedc11afd330e12ddcc8e5171a3202d7dbfacbbeb477075bb94605f"
      define_method(:install) do
        bin.install "aixgate"
      end
    end
  end

  test do
    system "#{bin}/aixgate version"
  end
end
