# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aixgate < Formula
  desc "A deny-by-default sandbox for AI coding agents (Claude Code, Cursor, Aider, Codex)."
  homepage "https://github.com/aixgo-dev/aixgate"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "db6860aa047f13c242fd361636f3dda37b4ec2a29fbf068fcfdb015e7afaf6f1"

      define_method(:install) do
        bin.install "aixgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Darwin_arm64.tar.gz"
      sha256 "5f3e6de0618def9b85b5d8595e166803958f419c6a69611b0815208584320b2d"

      define_method(:install) do
        bin.install "aixgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Linux_x86_64.tar.gz"
      sha256 "156697c569d5e21b14fef8b676d012b43f3cf3b1c99fb7bb2b8e00df5bdb41fd"
      define_method(:install) do
        bin.install "aixgate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Linux_arm64.tar.gz"
      sha256 "10f6020b032822a87416549cf16b17ee1c3579ece074f321e0f9c40e49bde56d"
      define_method(:install) do
        bin.install "aixgate"
      end
    end
  end

  test do
    system "#{bin}/aixgate version"
  end
end
