# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aixgate < Formula
  desc "A deny-by-default sandbox for AI coding agents (Claude Code, Cursor, Aider, Codex)."
  homepage "https://github.com/aixgo-dev/aixgate"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "22e1a83ba8f9eef1af08813680fec5d766717453388c12ebc60159f84a8179b5"

      define_method(:install) do
        bin.install "aixgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Darwin_arm64.tar.gz"
      sha256 "0c189908a5704e999bdebbfb595438c7bd462c90e21b9669592d9027be764648"

      define_method(:install) do
        bin.install "aixgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Linux_x86_64.tar.gz"
      sha256 "fd7aeb1c6308362f1c7da7969cd2c81aff3569b24707345aa7319b44d069a3e3"
      define_method(:install) do
        bin.install "aixgate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aixgo-dev/aixgate/releases/download/v0.1.0/aixgate_0.1.0_Linux_arm64.tar.gz"
      sha256 "c10678682b4ab1c5c400b4f7c52be419b588b972835fa3ad22d65d721d52374b"
      define_method(:install) do
        bin.install "aixgate"
      end
    end
  end

  test do
    system "#{bin}/aixgate version"
  end
end
